POST http://localhost:3005/student
Content-Type: application/json

{
  "Name":"Kiran",
  "StudentID":7679576,
  "StudentYear":"4th Year",
  "StudentCourse":"ECE",
  "Address":"4-8/9,Miyapur",
  "State":"Telangana"
}
###

GET http://localhost:3005/student

### 
GET http://localhost:3005/student/r


